- hosts: ws-1
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/nginx_1.yml

- hosts: ws-2
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/nginx_2.yml

- hosts: lb-1
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/keepalived_master.yml

- hosts: lb-1
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/haproxy.yml

- hosts: lb-2
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/keepalived_backup.yml

- hosts: lb-2
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/haproxy.yml