---
- name: Ensure keepalived is installed
  yum: name=keepalived
  when: ansible_os_family == "RedHat"

- name: Ensure keepalived conf is set
  template: >
    src=templates/keepalived_master.conf.j2
    dest=/etc/keepalived/keepalived.conf
- name: Ensure keepalived is started
  service: >
    name=keepalived
    state=started
    enabled=yes